x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  vaultwarden-ts:
    extends:
      file: ../common/tailscale.yml
      service: tailscale-base
    hostname: raziel
    container_name: vaultwarden-ts
    env_file:
      - ../.env.tailscale
    volumes:
      - ./state:/var/lib/tailscale
      - ./ts-config:/config
    logging: *default-logging
  vaultwarden:
    image: vaultwarden/server:1.37.3
    container_name: vaultwarden
    restart: unless-stopped
    logging: *default-logging
    network_mode: "service:vaultwarden-ts"
    environment:
      DOMAIN: "https://raziel.your-tailnet.ts.net"
    volumes:
      - /srv/vaultwarden:/data
      - /etc/localtime:/etc/localtime:ro
