x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  adguardhome-ts:
    extends:
      file: ../common/tailscale.yml
      service: tailscale-base
    hostname: aegis
    container_name: adguardhome-ts
    env_file:
      - ../.env.tailscale
    volumes:
      - ./state:/var/lib/tailscale
      - ./ts-config:/config
    logging: *default-logging
  adguardhome:
    image: adguard/adguardhome:v0.107.77
    container_name: adguardhome
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - /srv/adguardhome/work:/opt/adguardhome/work
      - /srv/adguardhome/conf:/opt/adguardhome/conf
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    network_mode: "service:adguardhome-ts"
