x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  beszel-ts:
    extends:
      file: ../common/tailscale.yml
      service: tailscale-base
    hostname: argus
    container_name: beszel-ts
    env_file:
      - ../.env.tailscale
    volumes:
      - ./state:/var/lib/tailscale
      - ./ts-config:/config
    logging: *default-logging
  beszel:
    image: henrygd/beszel:0.20.0
    container_name: beszel
    restart: unless-stopped
    logging: *default-logging
    network_mode: "service:beszel-ts"
    volumes:
      - /srv/beszel:/beszel_data
      - /etc/localtime:/etc/localtime:ro
  beszel-agent:
    image: henrygd/beszel-agent:0.18.8
    container_name: beszel-agent
    restart: unless-stopped
    logging: *default-logging
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      # Do not remove quotes around the key
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK0f6IM8UZ7ZlZGDJFGUE+r1C/16rVgq12lxfhtmONXt'
      FILESYSTEM: nvme0n1
