x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  karakeep-ts:
    extends:
      file: ../common/tailscale.yml
      service: tailscale-base
    hostname: tagnest
    container_name: karakeep-ts
    env_file:
      - ../.env.tailscale
    volumes:
      - ./state:/var/lib/tailscale
      - ./ts-config:/config
    logging: *default-logging
  karakeep:
    container_name: karakeep
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    logging: *default-logging
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - /mnt/data/hoarder:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://localhost:7700
      BROWSER_WEB_URL: http://localhost:9222
      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
    network_mode: "service:karakeep-ts"
  chrome:
    container_name: karakeep_chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    logging: *default-logging
    network_mode: "service:karakeep-ts"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    container_name: karakeep_meilisearch
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    logging: *default-logging
    env_file:
      - .env
    network_mode: "service:karakeep-ts"
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
      - /etc/localtime:/etc/localtime:ro

volumes:
  meilisearch:
