x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  searxng-ts:
    extends:
      file: ../common/tailscale.yml
      service: tailscale-base
    hostname: savitri
    container_name: searxng-ts
    env_file:
      - ../.env.tailscale
    volumes:
      - ./state:/var/lib/tailscale
      - ./ts-config:/config
    logging: *default-logging
  searxng-redis:
    container_name: searxng-redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    network_mode: "service:searxng-ts"
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging: *default-logging

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:2026.8.4-c63835bd2
    restart: unless-stopped
    volumes:
      - ./searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    env_file:
      - .env
    environment:
      - SEARXNG_BASE_URL=https://savitri.your-tailnet.ts.net
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    network_mode: "service:searxng-ts"
    logging: *default-logging

volumes:
  valkey-data2:
  searxng-data:
